### ISSUE TITLE
About running this tool

### ISSUE THREAD

**Issue by riverstore** [hydro-dev/loj-download#1]
Can you please make a quick guidance to execute this tool? I run `yarn` and don't know what to do next ^^ .

Thanks a lot.

Regard.

**Comment by pt3155420267** [comment]
https://hydro.wang/index.php/archives/3/

**Comment by riverstore** [comment]
Thanks a lot. I tried and meet this error message. Look like that it's not implement yet.

`Error: Not implemented
`    at v2 (G:\Code\OJ system\Hydro\loj-download\index.ts:77:9)
`    at run (G:\Code\OJ system\Hydro\loj-download\index.ts:345:11)
`    at Object.<anonymous> (G:\Code\OJ system\Hydro\loj-download\index.ts:350:3)
`    at Module._compile (node:internal/modules/cjs/loader:1101:14)
`    at Object.loader (G:\Code\OJ system\Hydro\loj-download\bin\loj-download.js:32:19)
`    at Module.load (node:internal/modules/cjs/loader:981:32)
`    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
`    at Module.require (node:internal/modules/cjs/loader:1005:19)
`    at require (node:internal/modules/cjs/helpers:102:18)
`    at Object.<anonymous> (G:\Code\OJ system\Hydro\loj-download\bin\loj-download.js:35:1)

Regard.
